version: '3.1'
services:
  # PostgreSQL container
  postgres: 
    image: postgres
    container_name: postgres
    environment: 
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=12345678
    volumes:
      - './data:/var/lib/postgresql/data'
      - './dumps:/dumps'
    ports:
      - "5432:5432"

  
  # pgAdmin 4 container
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"

  # redis container
  redis:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6379:6379"